name: Continuous Integration
on: [push]

jobs:
  build:
    name: Build and Test
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Setup dotnet
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: '6.0.x'
    - name: Build
      run: dotnet build
    - name: Setup tests
      working-directory: ./DotnetTemplate.Web
      run: |
        npm install
    - name: Test
      working-directory: ./DotnetTemplate.Web
      run: npm t
    - name: Lint
      working-directory: ./DotnetTemplate.Web
      run: npm run lint
